package com.nishantattrey.clipsync.ui.theme

import androidx.compose.ui.graphics.Color

internal val LightPrimary = Color(0xFF1C1F21)
internal val LightOnPrimary = Color(0xFFFFFFFF)
internal val LightPrimaryContainer = Color(0xFFE7EAEB)
internal val LightOnPrimaryContainer = Color(0xFF17191B)
internal val LightSecondary = Color(0xFF505659)
internal val LightOnSecondary = Color(0xFFFFFFFF)
internal val LightSecondaryContainer = Color(0xFFE9ECEC)
internal val LightOnSecondaryContainer = Color(0xFF24282A)
internal val LightBackground = Color(0xFFF7F8F8)
internal val LightOnBackground = Color(0xFF17191B)
internal val LightSurface = Color(0xFFFDFDFD)
internal val LightSurfaceContainer = Color(0xFFF0F2F2)
internal val LightSurfaceContainerHigh = Color(0xFFE7EAEA)
internal val LightOnSurface = Color(0xFF17191B)
internal val LightOnSurfaceVariant = Color(0xFF5B6265)
internal val LightOutline = Color(0xFF747C7F)
internal val LightOutlineVariant = Color(0xFFD5DADB)

internal val DarkPrimary = Color(0xFFEDEDED)
internal val DarkOnPrimary = Color(0xFF17191B)
internal val DarkPrimaryContainer = Color(0xFF303538)
internal val DarkOnPrimaryContainer = Color(0xFFEDEDED)
internal val DarkSecondary = Color(0xFFC5CBC8)
internal val DarkOnSecondary = Color(0xFF25292B)
internal val DarkSecondaryContainer = Color(0xFF303538)
internal val DarkOnSecondaryContainer = Color(0xFFE8EBEA)
internal val DarkBackground = Color(0xFF121212)
internal val DarkOnBackground = Color(0xFFEDEDED)
internal val DarkSurface = Color(0xFF121212)
internal val DarkSurfaceContainer = Color(0xFF1C1C1E)
internal val DarkSurfaceContainerHigh = Color(0xFF242426)
internal val DarkOnSurface = Color(0xFFEDEDED)
internal val DarkOnSurfaceVariant = Color(0xFF8A8A8E)
internal val DarkOutline = Color(0xFF6E6E73)
internal val DarkOutlineVariant = Color(0xFF2C2C2E)

val SyncSuccess = Color(0xFF2E9B62)
val SyncWarning = Color(0xFFC18A28)
val BookmarkGold = Color(0xFFD3A238)
val SyncFailure = Color(0xFFC94A47)
