package com.nishantattrey.clipsync.ui.theme

import androidx.compose.ui.graphics.Color

internal val LightPrimary = Color(0xFF006B5D)
internal val LightOnPrimary = Color(0xFFFFFFFF)
internal val LightPrimaryContainer = Color(0xFFC1EFE5)
internal val LightOnPrimaryContainer = Color(0xFF00201A)
internal val LightSecondary = Color(0xFF4B625C)
internal val LightOnSecondary = Color(0xFFFFFFFF)
internal val LightSecondaryContainer = Color(0xFFCDE8E0)
internal val LightOnSecondaryContainer = Color(0xFF071F1A)
internal val LightBackground = Color(0xFFF6F8F7)
internal val LightOnBackground = Color(0xFF171C1A)
internal val LightSurface = Color(0xFFFCFDFC)
internal val LightSurfaceContainer = Color(0xFFEDF1EF)
internal val LightSurfaceContainerHigh = Color(0xFFE5EAE7)
internal val LightOnSurface = Color(0xFF171C1A)
internal val LightOnSurfaceVariant = Color(0xFF414946)
internal val LightOutline = Color(0xFF727B77)
internal val LightOutlineVariant = Color(0xFFC1C9C5)

internal val DarkPrimary = Color(0xFF62D9C2)
internal val DarkOnPrimary = Color(0xFF00382F)
internal val DarkPrimaryContainer = Color(0xFF005044)
internal val DarkOnPrimaryContainer = Color(0xFF83F6DF)
internal val DarkSecondary = Color(0xFFB1CCC3)
internal val DarkOnSecondary = Color(0xFF1D352F)
internal val DarkSecondaryContainer = Color(0xFF344B45)
internal val DarkOnSecondaryContainer = Color(0xFFCDE8E0)
internal val DarkBackground = Color(0xFF0D1110)
internal val DarkOnBackground = Color(0xFFE1E5E2)
internal val DarkSurface = Color(0xFF111615)
internal val DarkSurfaceContainer = Color(0xFF181E1C)
internal val DarkSurfaceContainerHigh = Color(0xFF222927)
internal val DarkOnSurface = Color(0xFFE1E5E2)
internal val DarkOnSurfaceVariant = Color(0xFFBFC8C4)
internal val DarkOutline = Color(0xFF89938F)
internal val DarkOutlineVariant = Color(0xFF414946)

val SyncSuccess = Color(0xFF2E9B62)
val SyncWarning = Color(0xFFC18A28)
val BookmarkGold = Color(0xFFD3A238)
val SyncFailure = Color(0xFFC94A47)
