package com.nishantattrey.clipsync.ui.theme

import androidx.compose.ui.graphics.Color

internal val LightPrimary = Color(0xFF006F68)
internal val LightOnPrimary = Color(0xFFFFFFFF)
internal val LightPrimaryContainer = Color(0xFFC4F1EB)
internal val LightOnPrimaryContainer = Color(0xFF00201A)
internal val LightSecondary = Color(0xFF4D5F5D)
internal val LightOnSecondary = Color(0xFFFFFFFF)
internal val LightSecondaryContainer = Color(0xFFDCE8E6)
internal val LightOnSecondaryContainer = Color(0xFF071F1A)
internal val LightBackground = Color(0xFFF4F7F6)
internal val LightOnBackground = Color(0xFF171C1A)
internal val LightSurface = Color(0xFFFAFCFB)
internal val LightSurfaceContainer = Color(0xFFEAEFEE)
internal val LightSurfaceContainerHigh = Color(0xFFE1E7E5)
internal val LightOnSurface = Color(0xFF171C1A)
internal val LightOnSurfaceVariant = Color(0xFF414946)
internal val LightOutline = Color(0xFF727B77)
internal val LightOutlineVariant = Color(0xFFC1C9C5)

internal val DarkPrimary = Color(0xFF5CE1D3)
internal val DarkOnPrimary = Color(0xFF003733)
internal val DarkPrimaryContainer = Color(0xFF143B38)
internal val DarkOnPrimaryContainer = Color(0xFF89F5E8)
internal val DarkSecondary = Color(0xFFB7C4C2)
internal val DarkOnSecondary = Color(0xFF263332)
internal val DarkSecondaryContainer = Color(0xFF2B3535)
internal val DarkOnSecondaryContainer = Color(0xFFD4E2DF)
internal val DarkBackground = Color(0xFF0B0D0E)
internal val DarkOnBackground = Color(0xFFE1E5E2)
internal val DarkSurface = Color(0xFF101315)
internal val DarkSurfaceContainer = Color(0xFF181C1F)
internal val DarkSurfaceContainerHigh = Color(0xFF20262A)
internal val DarkOnSurface = Color(0xFFE1E5E2)
internal val DarkOnSurfaceVariant = Color(0xFFBFC8C4)
internal val DarkOutline = Color(0xFF89938F)
internal val DarkOutlineVariant = Color(0xFF414946)

val SyncSuccess = Color(0xFF2E9B62)
val SyncWarning = Color(0xFFC18A28)
val BookmarkGold = Color(0xFFD3A238)
val SyncFailure = Color(0xFFC94A47)
